### ISSUE TITLE
Missing one prerequisite

### ISSUE THREAD

**Issue by josiahjohnston** [briner/tsm2deb#2]
You should add `zip` to the list of prerequisites. I'm trying to restore into a fresh install of 14.04 Ubuntu server and zip wasn't installed yet. This gave an error/warning message on my first attempt:
- wrap ba
  -------
  ./tsm2deb: line 564: unzip: command not found
  convert.im6: no decode delegate for this image format `/tmp/magick-L0R5d4cX' @ error/constitute.c/ReadImage/544.
  convert.im6: no images defined`/root/install_files/tsm_7.1//ucberkeley-tsm-ba_7.1.0.3-0/usr/share/pixmaps/dsmwin32.png' @ error/convert.c/ConvertImageCommand/3044.
   dpkg-deb: building package `ucberkeley-tsm-ba' in`/root/install_files/tsm_7.1//ucberkeley-tsm-ba_7.1.0.3-0.deb'.

I cancelled the process, installed zip, and it worked fine.

**Comment by briner** [comment]
your welcome
