### ISSUE TITLE
Debian naming convention

### ISSUE THREAD

**Issue by itsbo** [briner/tsm2deb#4]
Hi,

Just a minor thought. All occurrence of 

SUB_DEB_BUILD=${TSM_ROOT}/${SUB_DEBNAME}_${TSM_VER}-${SUB_DEB_VER}

should be

SUB_DEB_BUILD=${TSM_ROOT}/${SUB_DEBNAME}_${TSM_VER}-${SUB_DEB_VER}_amd64

in order to conform to the Debian package naming convention. This way package-repositories will place the package correctly.

http://www.debian.org/doc/manuals/debian-faq/ch-pkg_basics#s-pkgname

**Comment by briner** [comment]
Than's for the report.

It has been integrated in (this)[https://github.com/briner/tsm2deb/commit/e02486125b71f8ff48998d37f22e3419e2ae58c1] change
